[theme]
base                   = "light"
primaryColor           = "#0F766E"
backgroundColor        = "#F1FAFB"
secondaryBackgroundColor = "#E2F4F3"
textColor              = "#1E293B"
font                   = "sans serif"

[server]
headless = true

[client]
toolbarMode = "minimal"
